"""add_is_admin_to_users

Revision ID: 0684902a9798
Revises: a11bd394f041
Create Date: 2026-07-10 15:09:09.560948
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0684902a9798'
down_revision: Union[str, None] = 'a11bd394f041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
