"""add_reset_code_to_users

Revision ID: 237d0993cc2d
Revises: 0684902a9798
Create Date: 2026-07-10 15:39:41.045424
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '237d0993cc2d'
down_revision: Union[str, None] = '0684902a9798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
