"""simplify_folder_no_nesting

Revision ID: a11bd394f041
Revises: 9e9dc0d6a498
Create Date: 2026-07-10 14:53:07.467220
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a11bd394f041'
down_revision: Union[str, None] = '9e9dc0d6a498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite 不支持直接 ALTER CONSTRAINT，用 batch mode
    with op.batch_alter_table('folders') as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.drop_column('parent_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('parent_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'])
    op.drop_column('folders', 'is_default')
    # ### end Alembic commands ###
